
server:
  port: 8080

spring:
    # mysql数据源
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/blog_data?characterEncoding=UTF-8
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    # 文件服务器设置
    http:
        multipart:
            max-file-size: 1MB
            max-request-size: 1MB

    data:
    # mongodb 数据源
        mongodb:
            uri: mongodb://localhost:27017/blog
    # elasticsearch 数据源
        elasticsearch:
            cluster-nodes: localhost:9300
            properties:
                transport:
                    tcp:
                        connection_timeout=120s

file:
    server:
        url: http://localhost:8080/upload
